### ISSUE TITLE
通过WeBASE-Codegen-Monkey生成的子工程无法启动，错误问题如下

### ISSUE THREAD

**Issue by jiahongwen** [WeBankFinTech/WeBASE-Codegen-Monkey#16]
**1. 管理后台部署helloworld的智能合约**
![image](https://user-images.githubusercontent.com/25731329/69849364-789b9a00-12b7-11ea-9da3-eacd3ec37a5a.png)
![image](https://user-images.githubusercontent.com/25731329/69849336-628dd980-12b7-11ea-8f46-9e5b3a799f4f.png)
**2. 安装文件结构如下**
![image](https://user-images.githubusercontent.com/25731329/69849594-24dd8080-12b8-11ea-966f-842b244fe548.png)
**3. 配置文件 application.properties  内容如下**
![image](https://user-images.githubusercontent.com/25731329/69849530-ed6ed400-12b7-11ea-9385-d4fcd62e7830.png)
**4. 执行generate_bee.sh过程如下**
![image](https://user-images.githubusercontent.com/25731329/69849918-f7450700-12b8-11ea-960a-9182d66f42b7.png)
![image](https://user-images.githubusercontent.com/25731329/69849946-0926aa00-12b9-11ea-8409-85639b132684.png)
![image](https://user-images.githubusercontent.com/25731329/69849959-117ee500-12b9-11ea-8ec1-d36a4995f176.png)
![image](https://user-images.githubusercontent.com/25731329/69849965-1774c600-12b9-11ea-84de-1e40c7db9372.png)
我是严格安装步骤来的，这块的资料比较少，希望官方给一点头绪

**Comment by dalaocu** [comment]
需要将application.properties里面的system.contractPackName配置修改为HelloWorld.java的包名。如com.webank.webasebee

修改完成后再重启一下。

**Comment by jiahongwen** [comment]
**按照您说的配置还是不行，如下：**

![image](https://user-images.githubusercontent.com/25731329/69860790-e94fb000-12d1-11ea-8149-b8e06d981c25.png)
![image](https://user-images.githubusercontent.com/25731329/69860993-506d6480-12d2-11ea-95eb-edd1116b5107.png)

**我的判断：
我感觉是数据源的问题，但是不知道哪里配置出了问题**

**我有几个疑问：**

1.这里的配置和生成的子系统里面的不一致，伊那个为主。
![image](https://user-images.githubusercontent.com/25731329/69860612-983fbc00-12d1-11ea-9f0a-ec6d2714610f.png)
2.我不配置智能合约时，单独启动 java -jar WeBASE-Collect-Bee-WeBASE-Collect-Bee-core1.2.0.jar 也报这个错误，是否工程有问题。

期待您的回复，谢谢！

**Comment by dalaocu** [comment]
你的system.orgId没有配置，需要配置一下。另外，请检查下数据库的配置是否正确，建议手动连接一下。
你贴的报错日志不全，前面执行的时候应该有其他的报错。

1. 这里的文档有误，应该为system.contractPackName
2. 如果配置不正确，无法正常启动。

**Comment by dalaocu** [comment]
system.baseProjectPath不对，请保留原有的值：../../WeBASE-Collect-Bee
